CREATE TABLE IF NOT EXISTS coluna (
    id SERIAL PRIMARY KEY,
    id_espaco INT NOT NULL REFERENCES espaco(id) ON DELETE CASCADE,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('A FAZER', 'FAZENDO', 'FEITO')),
    data_cadastro TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ordem INT NOT NULL
);